- app/common/translate.py
- requirements.txt
Library is requiring additional installation to function. Don't want to bother trying to install this on user machines, so removing and will figure out another way to tackle this.
> Remove nltk

- auto_translate/main.py
Completely redo to support both game files and network dialog with different types of lists and tags.
> Redo autotranslate (again)

- app/common/errors.py
- app/common/memory.py
- app/common/translate.py
- app/common/update.py
Update message boxes to use 0x1000 so that they are always on top. Consolidate message boxes into one function.
> refactor: Update message boxes

- app/run_clarity.ps1
Capture specific messaging seen a few times where anti-virus has always been the culprit and display error on certain condition.
> Capture venv creation output

- app/hooking/hook.py
- app/main.py
Split out hooks that will work without enabling an API translation service (`-c` param).
> Always hook, but split out API hooks

- app/clarity.py
Catch errors that happen during the walkthrough scanner to reduce noise, especially when the game is closed unexpectedly. Cleans up the console and logs when the player closes the game.
> Capture exceptions when walkthrough scanner stops unexpectedly

- .github/workflows/build-pr.yml
- .github/workflows/build-release.yml
Include all files in the csv folder of dqx-custom-translations when building a pr/release, which includes merge.xlsx.
> merge.xlsx is missing in the release zip

- app/hooking/network_text.py
Fixes:
```
Traceback (most recent call last):
File "<string>", line 7, in <module>
File "D:\\dqxclarity\hooking\network_text.py", line 51, in __init__
category = read_string(self.var_address + 40)  # var name is 40 bytes in
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\\dqxclarity\common\memory.py", line 77, in read_string
return PYM_PROCESS.read_string(address, bytes_to_read)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\\dqxclarity\pymem\__init__.py", line 959, in read_string
value = pymem.memory.read_string(self.process_handle, address, byte)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\\dqxclarity\pymem\memory.py", line 572, in read_string
buff = buff.decode()
^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 0: …
```
> fix: Catch UnicodeDecode errors and do nothing.

- app/clarity.py
- app/common/memory.py
- app/hooking/hide_hooks.py
Remove 299 exception handling as it's being handled in `scan_pattern_page` now, which is where these happen.
> Remove 299 handling

- app/clarity.py
We're doing a weird thing with clarity where we are infinitely scanning memory for strings. When we find certain patterns, we overwrite them.
This is a problem when memory is always changing; memory is being de-allocated and re-allocated at any given time. Something that was found with `pattern_scan_all` may no longer be the case anymore, but we could write over valid data that was allocated and cause crashes because of it.
This isn't going to fix 100% of these problems, but it should significantly reduce the chance of this happening by reading from the address immediately before writing to it. If the data doesn't match, the the previous read was stale and we throw it away altogether.
> Reread memory before writing.

- app/common/lib.py
- app/common/process.py
- app/updater.py
Let `subprocess` parse the output and just return a string. We only need to see if DQXGame.exe is visible.
> Another attempt at non-latin alphabet process parsing

- app/common/update.py
> fix: Close prompt if user cancels

- app/common/update.py
Change was unintentional and only used as a test.
> fix: fix default_path

- app/common/update.py
> feat: Add more messaging when can't find DQX folder.

- .github/workflows/build-release.yml
> ci: Add previous dat+idx file to new releases

- app/common/signatures.py
- app/hooking/corner_text.py
- app/hooking/hook.py
Add a hook that overwrites text in the top right when an NPC speaks.
->
> feat: add a corner text hook

- .pre-commit-config.yaml
remove pre-commit checks that aren't applicable to this repo anymore.
> chore: remove old precommit checks

- user_settings.ini
add launcher section defaults to default user settings file.
> chore: update default user_settings

- app/clarity.py
- app/common/translate.py
- app/hooking/network_text.py
- app/hooking/party.py
- app/hooking/player.py
* fix an issue where when a name has hiragana + katakana in it, it wasn't properly transliterating.
* rename function to more accurately describe what it does
> fix: transliterating names

- app/common/translate.py
> fix: Remove/replace some characters that are tripping up MTL.

- app/run_clarity.ps1
> fix: Check for msiexec before running Python installer

- app/common/update.py
Ensure the database only consists of contents in the glossary.csv file and nothing more.
> fix: regenerate glossary table contents every update.

- app/tests/test_memory.py
these tests are very inconsistent at the moment. this is a forked library and was a best effort, but need to revisit sometime.
> ci: disable unit tests for pymem

- app/common/config.py
- app/common/errors.py
- app/common/translate.py
- app/common/update.py
- app/main.py
- app/tests/test_config.py
- app/tests/test_translate.py
- Creates a `UserConfig` class that makes it easier to interact with the user_settings.ini file.
- Removes windows pop up messages
- Working on trying to strip out windows dependencies where appropriate
- Typing
- Add tests for `UserConfig` class
> refactor: config; strip some windows deps

- .gitignore
- app/clarity.py
- app/common/db_ops.py
- app/common/update.py
- app/hooking/party.py
- app/hooking/player.py
- app/main.py
- app/misc_files/README.md
- app/misc_files/name_overrides.json
Enable users to edit a local file to override their own player names and mytown names.
> feat: enable users to manage custom names

- app/common/update.py
Need to specify encoding type when reading file.
> fix: Encoding differences on other PCs

- app/common/update.py
When we update, we should make sure we're running with the latest updater.py versus being stuck with the previous until the user has downloaded the latest version.
> Grab updater.py before actually updating.

- .gitignore
- app/common/signatures.py
- app/common/update.py
- app/hooking/hook.py
adds fixed signatures for 7.4.
> patch 7.4: fixes

- app/clarity.py
- app/common/config.py
- app/common/measure.py
- app/common/translate.py
- app/common/translators/deepl.py
- app/common/translators/googletranslate.py
- app/common/translators/googletranslatefree.py
- app/hooking/dialog.py
- app/hooking/quest.py
- app/hooking/walkthrough.py
- app/launcher/dqxclarity.ahk
- user_settings.ini
- adds option to select "free" google translate option
- refactoring around translate functions
- adds a decorator to measure response times from api
> feat: add google translate option

- app/common/translate.py
We can't rely on mtl services to not mess with our string formatting. There have been too many inconsistencies where the mtl service will removes our line endings and return a single word, or in the case that made me look at this, Google Translate Free just completely ignores one of the list items.
This is of course a game breaking problem as not being able to select an item from a list blocks the player from being able to interact with that list item.
Moving forward, we'll translate each item in the list individually and re-construct the list.
> fix: Parse list items individually instead of as one word.

- app/common/translate.py
- app/common/translators/deepl.py
With the list parsing fixed, we should be able to enable this now.
> feat: enable "preferred quality" for deepl
