dqx-translation-project/dqxclarity

app/common/lib.py
Users that aren't using utf-8 supported encoding can't decode this string.
=> Decode text using the pc's locale.

.github/workflows/build-release.yml, RELEASES.md
The idea here is:
- Any commits to main will build a "dev" version of the current tag
- If we are on tag v4.0.0, a commit to main will make a pre-release and tag for v4.0.0-dev
- This was changed from automatically converting to v4.1.0 because this assumes the next tag already. We don't know what the next version will immediately be.
- Any existing assets attached to the dev release will be deleted and the latest zip will be attached instead
- When a new tag is pushed to the repository, the same tag (minus the v) will be written to the version.update file and committed
- We move the tag to the commit that made the change to version.updateso so that the tag includes the version bump
- This also kicks off a new official release with the tag that was pushed
It's similar to before, but there …
=> Update gha release

.gitattributes
Tell github to not run an archive on the entire repo when generating a source code zip.
=> chore: Ship blank source code zip

.github/workflows/build-pr.yml
Add an action that allows typing `/build` inside of a PR comment to upload an artifact to the build with a working packaged version for easier testing of PRs.
=> feat: Build zip for a PR

app/common/translate.py
Disable checking if the user didn't provide any keys or didn't check any translation service. It's possible the user wants to use some of the features, but not the translation features specifically.
=> Don't require a translation service to be enabled

app/hooking/hook.py
When a module is imported, the code at the top of the class is also executed (because it's global to the class and not part of the class's `__init__`). This is not the behavior I am expecting, so I am moving the imports into the function that uses the shellcode functions instead.
=> Move shellcode imports into the functions that use them.

app/clarity.py, app/common/lib.py, app/common/memory.py, app/common/process.py, app/common/update.py, app/hooking/dialog.py, app/hooking/easydetour.py, app/hooking/hide_hooks.py, app/hooking/hook.py, app/hooking/network_text.py, app/hooking/player.py, app/hooking/quest.py, app/main.py
dqxclarity has always had an issue where you couldn't import or run a majority of the program if DQXGame.exe wasn't open. This was because pymem was being called and used globally across the file on import of `common.memory`. These changes instead will instantiate a new pymem instance on init of the class, which means you no longer need dqx open to import different modules. This can help with writing tests and general usability during debugging.
=> Don't call direct memory operations and just import the class.

app/hooking/dialog.py, app/hooking/network_text.py, app/hooking/player.py, app/hooking/quest.py
Only initialize MemWriter once and store it as a global var in the class. This fixes a bug where MemWriter was being called every time on init, causing massive slowdowns/stuttering.
=> fix: Stuttering when calling hooks

app/common/memory.py, app/pymem/pattern.py
`pymem` is sometimes throwing this error when you're just standing still. In this instance, 299's happen when scanning through memory pages. `VirtualQueryEx `scans the page, then `pymem` reads the live page into a buffer. Problem is that the time between `VirtualQueryEx` scanning the page and `pymem` reading it, the underlying page protection has changed (in this case, rarely to 'No Access'), which generates the 299. We'll catch 299's during this operation and move on to the next page as what we would have read has been invalidated anyways.
Exception seen when scanning:
```python
2023-10-18 19:56:16.637 | ERROR    | clarity:run_scans:299 - An exception occurred. `dqxclarity` will exit.
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Program Files …
```
=> fix: (?) WinApi 299 errors

app/clarity.py
When we lose the walkthrough address, scan for it again before jumping back up to the top of the loop. Fixes #158.
=> Fix walkthrough scanner loop

app/run_clarity.ps1
Ensure we're setting the correct working directory before running anything below. This can be a problem if a user is overriding their working directory in a custom profile.
=> fix: Set working directory

app/common/process.py, app/updater.py
Use a windows command that produces an exit code when DQXGame.exe isn't found.
=> fix: Users not using English can't launch clarity when DQX isn't opened

app/common/process.py
Ran into an issue where a user was using unix's version of find, which won't work with how we're using it.
=> fix: Use the fully qualified path to Windows binaries.

app/hooking/network_text.py
We need to check the category prior to init'ing the dict. When you continue passed the "Important notice" screen, the network hook loads. We don't want the hook to generate the dict until after the player selects their character as we need to swap some placeholder tags first.
=> fix: Don't init the m00 dict too early

app/launcher/dqxclarity.ahk
Add a check for run_clarity.ps1 before running. Provide the user an error if it cannot find it.
=> feat: Send error if run_clarity.ps1 not found

.github/workflows/build-release.yml
fixes issue where the downloaded files were 0kb. just use a gha to do instead.
=> ci: fix uploading existing dat/idx during release

.github/workflows/_compile_launcher.yml, .github/workflows/build-pr.yml, .github/workflows/build-release.yml
- DRY out the `compile_launcher` workflow job
- fix: Exclude the launcher folder from the release zip
- feat: when pushing commits to main from ci, specify the service account's PAT so that we can bypass pull requests. this should also allow enabling PRs on the base branch now (no more accidental merges to main)
=> ci: cleanup workflows

app/clarity.py, app/common/memory.py, app/common/process.py, app/pymem/__init__.py, app/pymem/pattern.py
pymem's `pattern_scan_all` currently scans the entirety of the process's memory region using `scan_pattern_page` to iterate over each memory page to evaluate if we want to read it in and run a query against it.
clarity generally only cares about memory that:
- is of type "PRIVATE" or "MAPPED" (we don't care about memory that is already mapped to an image, which exists in a module)
- has anything but PAGE_READWRITE defined in its protections (if we're scanning for data, the intent is to modify it)
this adds a `data_only` flag to `pattern_scan` so that we only scan for readable, writable memory. This offers a slight boost (on my pc) of about 200ms when running the main `run_scans` loop. This isn't significant, but as we may scan several hundreds of times over the course of a game session, …
=> feat: Add ability to scan only for data pages

app/common/translate.py
DQX introduced a new <voice_nw ...> tag where the end of a line _must_ end in a `<br>`, or the text will continue to scroll passed the voice lines.
=> fix: Add processing logic for <br> tags at the end of voice lines.

app/launcher/dqxclarity.ahk, app/main.py
* Instead of expecting the user to have `powershell.exe` and `cmd.exe` in their PATH, use the fully qualified path to the executables instead.
* If the user installs in `C:\Program Files (x86)` (i.e: they tried to install it by the game or something), show an error telling the user to move it and exit. We can't typically save user settings or db changes when clarity is in this directory because of windows permissions.
=> feat: Launcher changes

app/common/translate.py
google does not preserve newlines when it returns its translation, so we preserve them by swapping them with `<br>`'s before we send the string off to be translated.
=> fix: google translate does not preserve newlines

.github/workflows/_compile_launcher.yml
Autohotkey's main webpage is fronted with Cloudflare; the download to their installer zip is failing in ci.
=> fix: use github asset url instead of autohotkey site.

app/hooking/network_text.py
New var names to watch:
- CAS_target = name of a player target in sugo, like "Frizz to <target>"
- C_STR2 = the name of the item that appears in the casino when it says "Wow! so and so won <item>! Congrats!"
- L_GOODS = the name of DQX cash shop items if you decide to buy them through the NPC in megistris
=> feat: Add new strings to track in network_text hook

app/launcher/dqxclarity.ahk, app/run_clarity.ps1
Fixes https://github.com/dqx-translation-project/dqxclarity/issues/288.
=> fix: allow empty args when passing to main.py.

app/clarity.py
Need to add local_mytown_names to the npcs list. For some reason, _some_ names are being found in the npc patterns.
=> fix: some mytown names not translating

app/hooking/network_text.py
Adds "EV_QUEST_NAME" which allows translation of the quest name during cutscenes when the "Accepted the quest <name>" appears.
=> feat: Translate quest name when accepting quest in dialogue window

app/pymem/pattern.py
When DQX is launched in SteamOS via wine, this protection is applied instead of what we'd usually see on Windows. This is necessary in order for us to scan for patterns within modules that have these protections.
=> feat: add PAGE_EXECUTE_WRITECOPY to allowed protections

app/common/update.py, app/main.py
parse ignore.py from dqx-custom-translations to remove strings from m00_strings table. this requires moving two download functions into one.
=> feat: clean up m00_strings table using ignore.py

app/hooking/dialog.py, app/hooking/network_text.py
fixes:
- random encounters where the game won't move dialogue forward or the dialogue behavior is incorrect
- dialogue hanging for 10-15 seconds to translate
=> freeze fix

app/common/measure.py, app/common/translate.py, app/common/translators/deepl.py, app/common/translators/googletranslate.py, app/common/translators/googletranslatefree.py
- When a translation reaches out and times out or fails, don't continue processing the string as it just returns just the glossary words instead
- Add consistent logging calls (use `log` as the logging call)
- Don't retry failed DeepL calls -- just fail once so that we aren't holding the thread up that the game runs on, making the player wait longer
- Reduce the timeout period when waiting for a response from DeepL so that we aren't hanging up the thread for long periods of time
=> fix: Don't write translation failures to the db.

app/common/translators/deepl.py
DeepL does not preserve newlines in their quality optimized model type.
With `model_type="prefer_quality_optimized"`:
```
"\nEast Area West Area Fashion Street In front of Fairy's Well In front of Megistris Castle"
```
Excluding `model_type`:
```
"\nEast Area\nWest Area\nFashion Street\nIn front of the fairy well\nIn front of Megistris Castle\n"
```
Without the newlines, this breaks select lists in game.
=> revert: deepl model type

app/common/translate.py
Just for Asfeld, adding `<br>` tags causes text to just not show up, so we'll exclude the forced `<br>` tag in voice lines just for these instances.
=> fix: Asfeld adding unneeded <br>'s in its voiced lines.

app/common/signatures.py, app/hooking/hook.py, app/hooking/network_text.py
Found a better place to hook to write over "network text", which makes it to where we don't need to truncate text like quest names or player names anymore.
=> Remove truncated strings seen in network text.
